import type {
  BoardDefinition,
  CompatibilityRule,
  ExposureDecisionStep,
  LaneDefinition,
  PacketTemplate,
  PolicyCheck,
  ResearchToolProfile,
  RegistrySpec,
  RouteRule,
  SkillRegistryEntry,
  SpecialistProfile,
  ToolScoreMemory,
  WidgetDefinition,
  WrapperRegistryEntry,
} from "@/lib/spidernet/types";

export const boardRegistry: BoardDefinition[] = [
  {
    id: "dash-001-input-data",
    code: "Dash 001",
    slug: "input-data",
    title: "Dash 001 SETU Input Terminal",
    shortTitle: "SETU Input Terminal",
    route: "/boards/input-data",
    icon: "input",
    order: 1,
    status: "live",
    visibility: "main",
    description:
      "Strict intake, packet construction, policy checks before routing, route preview, and manager preview inside the existing web shell.",
    shellSummary: "Locked intake board for packet capture, route preview, and policy-first routing.",
    command: "/intake",
    purposeLock: "input only",
  },
  {
    id: "dash-002-tools-store",
    code: "Dash 002",
    slug: "tools-store",
    title: "Dash 002 Research Tools",
    shortTitle: "Research Tools",
    route: "/boards/tools-store",
    icon: "tools",
    order: 2,
    status: "live",
    visibility: "main",
    description:
      "Research-only planning intelligence for tool comparison, viability scoring, route recommendation, and software exposure judgment.",
    shellSummary: "Research-only board for comparison, fit analysis, and route recommendation.",
    command: "/research",
    purposeLock: "research only",
  },
  {
    id: "dash-003-hive-agents",
    code: "Dash 003",
    slug: "hive-agents",
    title: "Dash 003 Hive Orchestrator",
    shortTitle: "Hive Orchestrator",
    route: "/boards/hive-agents",
    icon: "agents",
    order: 3,
    status: "live",
    visibility: "main",
    description:
      "Saarthi manager board for synthesis, policy visibility, routing outcomes, approvals, and Chitragupt readiness gates.",
    shellSummary: "Manager synthesis, routing, approval, and readiness orchestration.",
    command: "/route",
    purposeLock: "manager orchestration",
  },
  {
    id: "dash-004-setu-bridge",
    code: "Dash 004",
    slug: "setu-bridge",
    title: "Dash 004 Specialist Task Execution",
    shortTitle: "Specialist Task Execution",
    route: "/boards/setu-bridge",
    icon: "bridge",
    order: 4,
    status: "live",
    visibility: "main",
    description:
      "Worker belt for specialist contracts, wrapper registry linkage, skill registry, and explicit software exposure decisions.",
    shellSummary: "Specialist contracts, wrappers, skills, and exposure-path linkage.",
    command: "/assign",
    purposeLock: "execution only",
  },
  {
    id: "dash-005-observatory",
    code: "Dash 005",
    slug: "observatory",
    title: "Dash 005 Observatory",
    shortTitle: "Observatory",
    route: "/boards/observatory",
    icon: "observatory",
    order: 5,
    status: "live",
    visibility: "main",
    description:
      "Testing, simulation, wrapper linkage health, rollback readiness, policy failures, and score-memory health in one board.",
    shellSummary: "Operational health, policy failures, wrapper checks, and rollback posture.",
    command: "/status",
    purposeLock: "observability only",
  },
  {
    id: "dash-006-memory-ledger",
    code: "Dash 006",
    slug: "memory-ledger",
    title: "Dash 006 Memory & Ledger",
    shortTitle: "Memory & Ledger",
    route: "/boards/memory-ledger",
    icon: "ledger",
    order: 6,
    status: "live",
    visibility: "main",
    description:
      "Vault browser and append-only ledger for DNA, RUL, LIB, BLP, FTD, packets, wrappers, skills, scores, and local persistence state.",
    shellSummary: "Durable vaults, packets, ledger history, wrappers, skills, and score memory.",
    command: "/vault",
    purposeLock: "memory and ledger only",
  },
];

export const widgetRegistry: WidgetDefinition[] = [
  {
    id: "policy-intake",
    boardId: "dash-001-input-data",
    title: "Policy Intake",
    description: "Packet capture, policy checks, and route preview.",
    zone: "primary",
  },
  {
    id: "packet-templates",
    boardId: "dash-001-input-data",
    title: "Packet Templates",
    description: "Typed workflow packet model with persistence targets.",
    zone: "secondary",
  },
  {
    id: "research-comparison",
    boardId: "dash-002-tools-store",
    title: "Research Comparison",
    description: "Research-only tool comparison and exposure decisions.",
    zone: "primary",
  },
  {
    id: "saarthi-synthesis",
    boardId: "dash-003-hive-agents",
    title: "Saarthi Synthesis",
    description: "Consensus, conflicts, viable paths, and readiness gates.",
    zone: "primary",
  },
  {
    id: "execution-linkage",
    boardId: "dash-004-setu-bridge",
    title: "Execution Linkage",
    description: "Specialists, wrappers, skills, and compatibility registry.",
    zone: "primary",
  },
  {
    id: "observatory-signals",
    boardId: "dash-005-observatory",
    title: "Observatory Signals",
    description: "Policy failures, health states, and rollback readiness.",
    zone: "primary",
  },
  {
    id: "vault-ledger",
    boardId: "dash-006-memory-ledger",
    title: "Vault Ledger",
    description: "Local vault storage, append-only ledger, and score memory.",
    zone: "primary",
  },
];

export const laneRegistry: LaneDefinition[] = [
  {
    name: "Architect",
    mandate: "Shapes structure, routes, and contracts before build work.",
    primaryOutputs: "policy, skeleton, registries, research asks",
  },
  {
    name: "Builder",
    mandate: "Implements approved work packets inside the project skeleton.",
    primaryOutputs: "code, wrappers, docs, tests",
  },
  {
    name: "Auditor",
    mandate: "Verifies safety, correctness, test evidence, and gate readiness.",
    primaryOutputs: "audit findings, risk notes, gate evidence",
  },
  {
    name: "Operator",
    mandate: "Runs tools, commands, observability, and incident handling under guardrails.",
    primaryOutputs: "logs, runbooks, execution status",
  },
];

export const routeFamilyRegistry: RouteRule[] = [
  {
    route: "DNA",
    purpose: "Permanent identity, architecture truths, and non-negotiable principles.",
    trigger: "Material changes the system's enduring identity or philosophy.",
    owner: "Brahma ji",
  },
  {
    route: "RUL",
    purpose: "Operating law, safety constraints, and governance decisions.",
    trigger: "Material constrains future routing, permissions, or behavior.",
    owner: "Chitragupt",
  },
  {
    route: "LIB",
    purpose: "Reusable patterns, wrappers, templates, adapters, and shared practices.",
    trigger: "A result is broadly reusable across projects or agents.",
    owner: "Vishwakarma",
  },
  {
    route: "BLP",
    purpose: "Blueprint and build-plan items ready for structured execution.",
    trigger: "Work is implementation-ready and belongs in a project skeleton.",
    owner: "Mahish ji",
  },
  {
    route: "FTD",
    purpose: "Deferred but preserved future work.",
    trigger: "Useful work exists but should not block the current pass.",
    owner: "Krishna ji",
  },
];

export const packetTemplateRegistry: PacketTemplate[] = [
  {
    kind: "intake",
    name: "Intake Packet",
    purpose: "Capture source, context, attachments, and early routing.",
    requiredFields: ["packetId", "source", "objective", "classifications", "routes", "vaultTargets", "manager"],
    persistenceTarget: "packets/intake.json",
    nextHandoff: "Research Packet",
  },
  {
    kind: "research",
    name: "Research Packet",
    purpose: "Dispatch research questions and evaluation dimensions before execution.",
    requiredFields: ["packetId", "question", "dispatchedTools", "reportTargets", "evaluationDimensions", "manager"],
    persistenceTarget: "packets/research.json",
    nextHandoff: "Approval Packet",
  },
  {
    kind: "approval",
    name: "Approval Packet",
    purpose: "Record approvals, readiness scope, and permission needs.",
    requiredFields: ["packetId", "summary", "approvers", "readinessState", "approvalScope", "requiresUserPass"],
    persistenceTarget: "packets/approval.json",
    nextHandoff: "Execution Packet",
  },
  {
    kind: "execution",
    name: "Execution Packet",
    purpose: "Drive specialist assignment and tool exposure strategy.",
    requiredFields: ["packetId", "stageOwner", "specialists", "toolExposureDecision", "nextStage", "blockers"],
    persistenceTarget: "packets/execution.json",
    nextHandoff: "Validation Packet",
  },
  {
    kind: "validation",
    name: "Validation Packet",
    purpose: "Track testing, simulation, audit streams, and definition-of-done.",
    requiredFields: ["packetId", "testStreams", "simulationStreams", "auditStreams", "definitionOfDone", "gatekeeper"],
    persistenceTarget: "packets/validation.json",
    nextHandoff: "Pass Packet",
  },
  {
    kind: "pass",
    name: "Pass Packet",
    purpose: "Record pass or fail, ledger routes, closeout artifacts, and history.",
    requiredFields: ["packetId", "decision", "ledgerRoutes", "retrospectiveTargets", "closeoutArtifacts", "signedBy"],
    persistenceTarget: "packets/pass.json",
    nextHandoff: "ledger append",
  },
];

export const exposureDecisionLadder: ExposureDecisionStep[] = [
  {
    key: "api",
    label: "API",
    description: "Preferred when the web product can safely expose a stable server-side path.",
    idealFor: "durable reads, writes, and controlled web actions",
    approvalWeight: "low",
    status: "live",
  },
  {
    key: "cli",
    label: "CLI",
    description: "Use for repo-local commands that are deterministic and already part of verification.",
    idealFor: "lint, build, scripted validation, local maintenance",
    approvalWeight: "medium",
    status: "live",
  },
  {
    key: "browser_automation",
    label: "Browser automation",
    description: "Use only when UI behavior needs automation and a stable script exists.",
    idealFor: "future UI checks and regression runs",
    approvalWeight: "high",
    status: "prepared",
  },
  {
    key: "desktop_automation",
    label: "Desktop automation",
    description: "Keep as an architecture option only when the web product cannot reasonably cover the workflow.",
    idealFor: "desktop-only tools outside the web shell",
    approvalWeight: "high",
    status: "prepared",
  },
  {
    key: "manual_hold",
    label: "Manual hold",
    description: "Default stop when confidence, permissions, or wrapper readiness is not good enough.",
    idealFor: "unsafe reach, weak evidence, approval gaps",
    approvalWeight: "high",
    status: "live",
  },
];

export const policyRegistry: PolicyCheck[] = [
  {
    id: "policy-research",
    name: "is this research",
    decisionRule: "If the task primarily compares, evaluates, plans, or gathers evidence, keep it in Dash 002.",
    actionIfTrue: "Build a research packet and do not unlock execution.",
    gateOwner: "Saarthi",
  },
  {
    id: "policy-build",
    name: "is this build",
    decisionRule: "If the task changes code, wrappers, docs, or project structure, it becomes a controlled execution flow.",
    actionIfTrue: "Require approval and execution packets.",
    gateOwner: "Saarthi",
  },
  {
    id: "policy-danger",
    name: "is this dangerous",
    decisionRule: "If the tool reach can mutate systems, accounts, browser state, desktop state, or privileged local assets, elevate controls.",
    actionIfTrue: "Tighten permissions, logs, audit, and isolation.",
    gateOwner: "Chitragupt",
  },
  {
    id: "policy-approval",
    name: "does it need approval",
    decisionRule: "If the change affects production behavior, policy, exposure path, or durable memory, approval is mandatory.",
    actionIfTrue: "Hold at the approval gate until evidence exists.",
    gateOwner: "Core Review",
  },
  {
    id: "policy-ftd",
    name: "should it go to FTD",
    decisionRule: "If it is valid but not on the critical path, move it out of the active build lane.",
    actionIfTrue: "Append to FTD and keep the main packet clean.",
    gateOwner: "Krishna ji",
  },
  {
    id: "policy-exposure",
    name: "tool exposure path",
    decisionRule: "Choose API, CLI, browser automation, desktop automation, or manual hold based on reliability and worth-doing.",
    actionIfTrue: "Record the decision in the wrapper registry and execution packet.",
    gateOwner: "Saarthi",
  },
];

export const registryCatalog: RegistrySpec[] = [
  {
    name: "board registry",
    purpose: "Locks board names, routes, and purpose boundaries.",
    contents: "board id, command, purpose lock, subtitle",
    authority: "SETU shell",
  },
  {
    name: "tool registry",
    purpose: "Tracks available research tools and posture.",
    contents: "tool profiles, specialty, safety stance, execution reach",
    authority: "Dash 002",
  },
  {
    name: "compatibility registry",
    purpose: "Defines tool pairings and discouraged paths.",
    contents: "works together, asks help, review, handoff, caution",
    authority: "Dash 004",
  },
  {
    name: "wrapper registry",
    purpose: "Tracks software exposure choices.",
    contents: "software, exposure path, status, why, guardrails",
    authority: "Dash 004 / Dash 006",
  },
  {
    name: "skill registry",
    purpose: "Tracks discoverable skills and generation posture.",
    contents: "skill name, discovery metadata, purpose, state",
    authority: "Dash 004",
  },
  {
    name: "policy registry",
    purpose: "Records routing law and escalation rules.",
    contents: "policy checks, gate owners, dangerous thresholds",
    authority: "Dash 003",
  },
  {
    name: "approval registry",
    purpose: "Captures readiness and signoff flows.",
    contents: "approvers, scope, evidence expectations",
    authority: "Dash 003",
  },
  {
    name: "score registry",
    purpose: "Stores tool score memory for better routing.",
    contents: "success, cost, latency, rework, failure, task family",
    authority: "Dash 006",
  },
];

export const researchToolRegistry: ResearchToolProfile[] = [
  {
    id: "research-codex",
    name: "Codex Research Pass",
    specialty: "Repo-grounded architecture and integration analysis",
    bestUse: "Current repo comparison, coupling analysis, and implementation pathing",
    limitations: "Needs source truth and should not fake external certainty",
    footprint: "local + cloud",
    cost: "medium",
    latency: "medium",
    confidence: "high",
    taskFamily: "repo analysis and implementation planning",
    advisoryRole: "Produces manager-ready technical reports",
    reviewRole: "Checks whether plans match current wiring",
    apiSuitability: "high",
    cliSuitability: "high",
    browserSuitability: "medium",
    desktopSuitability: "low",
    worthDoingScore: 9,
    bottleneckRemovalScore: 8,
    longTermScore: 9,
    confidenceScore: 0.88,
    health: "healthy",
    connectorStatus: "connected",
    researchOnly: true,
  },
  {
    id: "research-claude",
    name: "Claude Deliberation",
    specialty: "Tradeoff synthesis and conflict framing",
    bestUse: "Consensus or conflict comparison and policy review",
    limitations: "Needs manager grounding to stay tied to repo reality",
    footprint: "cloud",
    cost: "medium",
    latency: "medium",
    confidence: "medium",
    taskFamily: "planning and objections analysis",
    advisoryRole: "Frames alternatives and likely objections",
    reviewRole: "Second-opinion synthesis",
    apiSuitability: "medium",
    cliSuitability: "low",
    browserSuitability: "low",
    desktopSuitability: "low",
    worthDoingScore: 8,
    bottleneckRemovalScore: 7,
    longTermScore: 7,
    confidenceScore: 0.79,
    health: "watch",
    connectorStatus: "partial",
    researchOnly: true,
  },
  {
    id: "research-perplexity",
    name: "Perplexity Retrieval",
    specialty: "Fast outward-looking evidence gathering",
    bestUse: "Version-sensitive research and options scans",
    limitations: "Needs source quality review before planning becomes policy",
    footprint: "cloud",
    cost: "medium",
    latency: "low",
    confidence: "medium",
    taskFamily: "external evidence and discovery",
    advisoryRole: "Provides evidence packs for manager review",
    reviewRole: "Cross-checks freshness assumptions",
    apiSuitability: "high",
    cliSuitability: "low",
    browserSuitability: "medium",
    desktopSuitability: "low",
    worthDoingScore: 7,
    bottleneckRemovalScore: 8,
    longTermScore: 6,
    confidenceScore: 0.74,
    health: "healthy",
    connectorStatus: "connected",
    researchOnly: true,
  },
];

export const specialistRegistry: SpecialistProfile[] = [
  {
    id: "specialist-architect",
    name: "Architect lane",
    workProfile: "Plans the structure before any build work starts",
    specialty: "routing law, registries, templates, board contracts",
    inputContract: "approved intake and research packets",
    outputContract: "BLP-ready plan, route families, wrapper decisions",
    advisoryCompatibility: "Saarthi",
    helperCompatibility: "Auditor lane",
    handoffCompatibility: "Builder lane",
    safeUseNotes: "Must not bypass policy checks or board purpose locks",
  },
  {
    id: "specialist-builder",
    name: "Builder lane",
    workProfile: "Implements approved work inside the project skeleton",
    specialty: "code changes, docs, wrappers, persistence, setup",
    inputContract: "execution packets with approved exposure path",
    outputContract: "code, docs, tests, and linkage evidence",
    advisoryCompatibility: "Architect lane",
    helperCompatibility: "Operator lane",
    handoffCompatibility: "Auditor lane",
    safeUseNotes: "Build work stays repo-scoped and must update logs",
  },
  {
    id: "specialist-auditor",
    name: "Auditor lane",
    workProfile: "Checks correctness, safety, and readiness",
    specialty: "policy verification, test evidence, rollback posture",
    inputContract: "validation packets and execution evidence",
    outputContract: "findings, readiness state, pass or hold recommendation",
    advisoryCompatibility: "Chitragupt",
    helperCompatibility: "Builder lane",
    handoffCompatibility: "Operator lane",
    safeUseNotes: "Can hold release if evidence is incomplete",
  },
  {
    id: "specialist-operator",
    name: "Operator lane",
    workProfile: "Runs approved commands and monitors health",
    specialty: "local runs, wrappers, logs, observability, restart path",
    inputContract: "approved execution or validation packets",
    outputContract: "runtime status, logs, smoke checks, rollback proof",
    advisoryCompatibility: "Saarthi",
    helperCompatibility: "Builder lane",
    handoffCompatibility: "Auditor lane",
    safeUseNotes: "Must obey the chosen exposure path and manual holds",
  },
];

export const compatibilityRegistry: CompatibilityRule[] = [
  {
    id: "compat-codex-wrapper",
    pairing: "Codex Research Pass + wrapper registry",
    worksTogether: "Codex identifies the exposure path and wrapper guardrails.",
    asksHelpFrom: "Auditor lane for risk review",
    reviewPath: "Dash 003 -> Dash 004 -> Dash 005",
    handoffPath: "Research packet -> execution packet -> observatory check",
    caution: "Do not upgrade prepared wrappers to live without observability evidence.",
  },
  {
    id: "compat-builder-operator",
    pairing: "Builder lane + Operator lane",
    worksTogether: "Builder lands the change and Operator proves restart path.",
    asksHelpFrom: "Auditor lane for validation hold or release",
    reviewPath: "Dash 004 -> Dash 005",
    handoffPath: "Execution packet -> validation packet",
    caution: "Operator should not invent new build scope while validating.",
  },
  {
    id: "compat-research-manager",
    pairing: "Dash 002 Research Tools + Saarthi",
    worksTogether: "Research tools feed comparison evidence into manager synthesis.",
    asksHelpFrom: "Architect lane when route families need adjustment",
    reviewPath: "Dash 002 -> Dash 003",
    handoffPath: "Research packet -> approval packet",
    caution: "Dash 002 remains research-only and must not execute live changes.",
  },
];

export const wrapperRegistrySeed: WrapperRegistryEntry[] = [
  {
    id: "wrapper-next-api",
    software: "Next.js server actions",
    exposurePath: "api",
    status: "live",
    why: "Best fit for durable packet reads inside the web product.",
    guardrails: "Keep file writes server-side and repo-local only.",
    linkedBoards: ["dash-001-input-data", "dash-006-memory-ledger"],
    linkedPacketKinds: ["intake", "research", "approval", "execution", "validation", "pass"],
  },
  {
    id: "wrapper-npm-cli",
    software: "npm build and lint",
    exposurePath: "cli",
    status: "live",
    why: "Repo validation is already CLI-native and repeatable.",
    guardrails: "Run inside project root and record failures in logs.",
    linkedBoards: ["dash-004-setu-bridge", "dash-005-observatory"],
    linkedPacketKinds: ["execution", "validation"],
  },
  {
    id: "wrapper-browser",
    software: "browser automation",
    exposurePath: "browser_automation",
    status: "prepared",
    why: "Useful for future UI checks but not yet wired in this phase.",
    guardrails: "Enable only after explicit policy review and stable scripts.",
    linkedBoards: ["dash-005-observatory"],
    linkedPacketKinds: ["validation"],
  },
  {
    id: "wrapper-desktop",
    software: "desktop automation",
    exposurePath: "desktop_automation",
    status: "prepared",
    why: "Referenced by the architecture but intentionally not ported from Tk.",
    guardrails: "Keep web repo as main product and hold desktop actions by default.",
    linkedBoards: ["dash-004-setu-bridge"],
    linkedPacketKinds: ["execution"],
  },
  {
    id: "wrapper-manual",
    software: "manual hold",
    exposurePath: "manual_hold",
    status: "live",
    why: "Required fallback when exposure reliability or permissions are weak.",
    guardrails: "Blocks routing until owner review is complete.",
    linkedBoards: ["dash-003-hive-agents", "dash-005-observatory"],
    linkedPacketKinds: ["approval", "execution", "validation"],
  },
];

export const skillRegistrySeed: SkillRegistryEntry[] = [
  {
    id: "skill-openai-docs",
    skillName: "openai-docs",
    discovery: "Codex system skill",
    purpose: "Official documentation lookup for OpenAI-specific work",
    currentState: "live",
    linkedBoard: "dash-002-tools-store",
  },
  {
    id: "skill-imagegen",
    skillName: "imagegen",
    discovery: "Codex system skill",
    purpose: "Bitmap generation when UI or asset work needs raster output",
    currentState: "live",
    linkedBoard: "dash-004-setu-bridge",
  },
  {
    id: "skill-skill-installer",
    skillName: "skill-installer",
    discovery: "Codex system skill",
    purpose: "Controlled skill installation when future execution needs it",
    currentState: "prepared",
    linkedBoard: "dash-004-setu-bridge",
  },
];

export const scoreMemorySeed: ToolScoreMemory[] = [
  {
    id: "score-codex",
    tool: "Codex Research Pass",
    successRate: "high",
    cost: "medium",
    latency: "medium",
    reworkNeeded: "low",
    failureType: "stale assumptions when source files are skipped",
    bestTaskFamily: "repo-grounded architecture merge",
  },
  {
    id: "score-npm-build",
    tool: "npm build",
    successRate: "high",
    cost: "low",
    latency: "medium",
    reworkNeeded: "low",
    failureType: "type or import breakage",
    bestTaskFamily: "release validation",
  },
  {
    id: "score-ollama",
    tool: "Ollama local",
    successRate: "unknown",
    cost: "low",
    latency: "medium",
    reworkNeeded: "medium",
    failureType: "endpoint not configured",
    bestTaskFamily: "future local model inference",
  },
];
